CALL purgecss --css pages/dsns.dev/static/css/bulma.min.css --content pages/dsns.dev/index.html --output pages/dsns.dev/min.css
::CALL purgecss --css pages/dsns.dev/static/css/bulma.min.css --content pages/dsns.dev/birthdays/index.html --output pages/dsns.dev/birthdays/min.css
CALL purgecss --css pages/dsns.dev/static/css/bulma.min.css --content pages/dsns.dev/christmas/index.html --output pages/dsns.dev/christmas/min.css
CALL purgecss --css pages/dsns.dev/static/css/bulma.min.css --content pages/dsns.dev/difference/index.html --output pages/dsns.dev/difference/min.css
CALL purgecss --css pages/dsns.dev/static/css/bulma.min.css --content pages/dsns.dev/electric/index.html --output pages/dsns.dev/electric/min.css
CALL purgecss --css pages/dsns.dev/static/css/bulma.min.css --content pages/dsns.dev/ip/index.html --output pages/dsns.dev/ip/min.css
CALL purgecss --css pages/dsns.dev/static/css/bulma.min.css --content pages/dsns.dev/level/index.html --output pages/dsns.dev/level/min.css
CALL purgecss --css pages/dsns.dev/static/css/bulma.min.css --content pages/dsns.dev/mp3/index.html --output pages/dsns.dev/mp3/min.css
CALL purgecss --css pages/dsns.dev/static/css/bulma.min.css --content pages/dsns.dev/ppi/index.html --output pages/dsns.dev/ppi/min.css
CALL purgecss --css pages/dsns.dev/static/css/bulma.min.css --content pages/dsns.dev/projects/index.html --output pages/dsns.dev/projects/min.css
CALL purgecss --css pages/dsns.dev/static/css/bulma.min.css --content pages/dsns.dev/recentgames/index.html --output pages/dsns.dev/recentgames/min.css
CALL purgecss --css pages/dsns.dev/static/css/bulma.min.css --content pages/dsns.dev/speedtest/index.html --output pages/dsns.dev/speedtest/min.css
CALL purgecss --css pages/dsns.dev/static/css/bulma.min.css --content pages/dsns.dev/webcam/index.html --output pages/dsns.dev/webcam/min.css
CALL purgecss --css pages/dsns.dev/static/css/bulma.min.css --content pages/dsns.dev/whois/index.html --output pages/dsns.dev/whois/min.css